### ISSUE TITLE
Comment and instance have different length

### ISSUE THREAD

**Issue by maplewizard** [c-amr/camr#12]
I use 
```
python amr_parsing.py -m preprocess --amrfmt amr data/del.txt
```
and get the following result:
```
Traceback (most recent call last):
  File "amr_parsing.py", line 436, in <module>
    main()
  File "amr_parsing.py", line 169, in main
    instances = preprocess(amr_file,START_SNLP=True,INPUT_AMR=args.amrfmt, PRP_FORMAT=args.prpfmt)
  File "/home/me/workbench/amr/camr/preprocessing.py", line 372, in preprocess
    _write_tok_amr(tok_amr_filename,amr_file,instances)
  File "/home/me/workbench/amr/camr/preprocessing.py", line 124, in _write_tok_amr
    output_tok.write(comment_list[i])
IndexError: list index out of range
```
I found that the sentence "Has history given us too many lessons?, 530, 412, 64" was splited into two sentence and thus has different number with the comment.
Could you please tell me how to solve this issue?

**Comment by ypuzikov** [comment]
Stanford CoreNLP default.properties file contains properties for each of the annotators used.
Set the `ssplit.eolonly=true` property in `./stanfordnlp/default.properties` file. This will force CoreNLP to split sentences at newlines only.

See here: https://stanfordnlp.github.io/CoreNLP/ssplit.html
