### ISSUE TITLE
ImportError: No module named bllipparser.ModelFetcher

### ISSUE THREAD

**Issue by deepaca** [c-amr/camr#20]
While running the preprocessing command:
python2 amr_parsing.py -m preprocess a.txt

I got the following error. 

Read token,lemma,name entity file a.txt.prp...

Traceback (most recent call last):
  File "amr_parsing.py", line 436, in <module>
    main()
  File "amr_parsing.py", line 169, in main
    instances = preprocess(amr_file,START_SNLP=True,INPUT_AMR=args.amrfmt, PRP_FORMAT=args.prpfmt)
  File "/home/teqip-ii-cse-nlp-01-01/project/AMR/camr-master/preprocessing.py", line 504, in preprocess
    dparser.parse(tok_sent_filename)
  File "/home/teqip-ii-cse-nlp-01-01/project/AMR/camr-master/depparser.py", line 24, in parse
    from bllipparser.ModelFetcher import download_and_install_model
ImportError: No module named bllipparser.ModelFetcher

**Comment by deepaca** [comment]
This could be resolved by 

sudo pip install bllipparser.
