### ISSUE TITLE
About retraining

### ISSUE THREAD

**Issue by dopc** [c-amr/camr#23]
Hey,
I am trying to retrain the parser, but in the last step;

[path_to_train_amr_file],
[path_to_dev_amr_file]

I did not figure out what will I give to the parser for these two.
I tried many of things and have their logs.
Any help or explanation?

Thanks.

**Comment by dopc** [comment]
Connected to pydev debugger (build 183.5912.18)
Parser Config:
Incorporate Coref Information: False
Incorporate SRL Information: False
Substitue the normal name entity tag with rich name entity tag: False
Using verbalization list: True
Using charniak parser trained on ontonotes: wsj
Dependency parser used: stdconv+charniak
Read token,lemma,name entity file amrs.sent.prp...

Read dependency file amrs.sent.tok.charniak.parse.dep...
Read token,lemma,name entity file amr_train.sent.prp...

Read dependency file amr_train.sent.tok.charniak.parse.dep...
Importing feature generator!
BEGIN TRAINING!
shuffling training instances
Iteration: 1
Traceback (most recent call last):
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/dpc/ders/AMR/camr-master/amr_parsing.py", line 436, in <module>
    main()
  File "/home/dpc/ders/AMR/camr-master/amr_parsing.py", line 351, in main
    parser.parse_corpus_train(train_instances)
  File "/home/dpc/ders/AMR/camr-master/parser.py", line 117, in parse_corpus_train
    _,state = self.parse(inst)
  File "/home/dpc/ders/AMR/camr-master/parser.py", line 301, in parse
    best_act_ind, best_label_index = self.get_best_act(scores,actions)#,argset)
  File "/home/dpc/ders/AMR/camr-master/parser.py", line 63, in get_best_act
    best_act_ind = np.argmax(map(np.amax,scores))
  File "/usr/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2505, in amax
    initial=initial)
  File "/usr/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

Process finished with exit code 1

So I'm taking this output when I use my amr_file which also have amr_file.amr.tok.aligned for [path_to_train_amr_file]

**Comment by dopc** [comment]
Fixed. Inconsistent stanfordcorenlp made me inconsistent.
Sorry for disturbing.

**Comment by dopc** [comment]
Parser Config:
Incorporate Coref Information: False
Incorporate SRL Information: False
Substitue the normal name entity tag with rich name entity tag: False
Using verbalization list: True
Using charniak parser trained on ontonotes: wsj
Dependency parser used: stdconv+charniak
Read token,lemma,name entity file amrs.sent.prp...

Read dependency file amrs.sent.tok.charniak.parse.dep...
Writing sentence file to amr_dev.sent
Read token,lemma,name entity file amr_dev.sent.prp...
Traceback (most recent call last):
  File "amr_parsing.py", line 436, in <module>
    main()
  File "amr_parsing.py", line 321, in main
    if args.dev: dev_instances = preprocess(args.dev,START_SNLP=False,INPUT_AMR=args.amrfmt,PRP_FORMAT=args.prpfmt)
  File "/home/dpc/ders/AMR/camr-master/preprocessing.py", line 355, in preprocess
    instances = proc1.parse(tmp_sent_filename)
  File "/home/dpc/ders/AMR/camr-master/stanfordnlp/corenlp.py", line 502, in parse
    result = self._parse(line)
  File "/home/dpc/ders/AMR/camr-master/stanfordnlp/corenlp.py", line 379, in _parse
    self.corenlp.read_nonblocking (4000, 0.3)
AttributeError: 'StanfordCoreNLP' object has no attribute 'corenlp'

I got this message finally. Is there anyone to help for this?
Sorry for disturbing.
Thanks.

**Comment by dopc** [comment]
I fixed this problem with using instances from Little Prince on [https://amr.isi.edu/download/amr-bank-v1.6.txt](url). Instances from amr-guideline github page didn't work.
Sorry for disturbing.
Thank you.

**Comment by dopc** [comment]
I fixed this problem with using instances from Little Prince on [https://amr.isi.edu/download/amr-bank-v1.6.txt](url). Instances from amr-guideline github page didn't work.
Sorry for disturbing.
Thank you.
